# -*- coding: utf-8 -*-
"""data_science_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_FBKg8Z9yenbx8k7qLg_Oe0vL1CwSgDi

#**Analisando as notas em geral**
"""

import pandas as pd

notas = pd.read_csv("ratings.csv")
notas.head()

notas.shape

notas.columns = ["usuarioId","filmeId","nota","momento"]
notas.head()

notas['nota'].unique()

notas['nota'].value_counts()

print(notas['nota'].mean())
print(notas['nota'].median())

notas.nota.plot(kind='hist')

notas.nota.describe()

import seaborn as sns
sns.boxplot(notas.nota)

"""#**Visualizando os filmes**"""

filmes = pd.read_csv("movies.csv")
filmes.columns=["filmeId","titulo","generos"]
filmes.head()

#media de notas de um determinado filme
notas.query("filmeId==1").nota.mean()

notas.query("filmeId==2").nota.mean()

#agrupando os filmes e suas médias de notas
medias_por_filme = notas.groupby("filmeId").mean()["nota"]

medias_por_filme.plot(kind='hist')

medias_por_filme.describe()

import matplotlib.pyplot as plt
plt.hist(medias_por_filme)
plt.title("Histograma da média dos filmes")

