# -*- coding: utf-8 -*-
"""imports.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EF59Lml8OFxSbp2EnOvkEvEt7qIMIKfh

# Tipos em uma lista
"""

lista = ['Guilherme', 28, True , '18']

for elemento in lista:
  print(f'O elemento {elemento} é do tipo: ', type(elemento))
#em uma mesma lista posso ter vários tipos de variáveis

"""# Import"""

from random import randrange, seed
#Este módulo implementa geradores de números pseudoaleatórios para várias distribuições.

seed(11)

randrange(0,11)

notas_matematica = []

for notas in range(8):
  notas_matematica.append(randrange(0,11))
notas_matematica

len(notas_matematica)

"""# Matplotlib"""

import matplotlib.pyplot as plt

x = list(range(1,9))
y = notas_matematica
plt.plot(x,y, marker='o')
plt.title('Notas de matemática')
plt.xlabel('Provas')
plt.ylabel('Notas')
plt.show()

notas_matematica

