# -*- coding: utf-8 -*-
"""lista_loop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t196m7u8o2uJoDEmBdH9qVnihgVs0ORO

# Lista
"""

idade = 22
idade

#verifica o tipo da variável
type(idade)

nome = 'Geneviê'
type(nome)

#cria-se uma lista colocando os colchetes e separando por vírgula
idades = [18, 22, 15, 50]
type(idades)

#idades[2] = 15
idades = [18, 22, 15, 50]
#         0   1    2    3
#         0   -3  -2  -1

#exclui-se o ultimo elemento listado
idades[0:3]

#exclui-se o primeiro elemento
idades [1:]

#mostra apenas o último
idades[-1]

"""# Laços e loops"""

idades

def verifica_idade(idade):
  if idade >= 18:
    print(f'{idade} anos de idade, tem permissão para dirigir')
  else:
    print(f'{idade} anos de idade, não tem permissão para dirigir')

for idade in idades:
  verifica_idade(idade)

def verifica_idade(idades):
  for idade in idades:
    if idade >= 18:
      print(f'{idade} anos de idade, tem permissão para dirigir')
  else:
    print(f'{idade} anos de idade, não tem permissão para dirigir')
verifica_idade(idades)
"""# Booleano"""

idade = 18
idade >=18

idade = 15
idade >=18

permissoes = []
idades = [20, 14, 40]

def verifica_idade(idades,permissoes):
  for idade in idades:
    if idade >= 18:
      permissoes.append(True)
    else:
        permissoes.append(False)
verifica_idade(idades,permissoes)

permissoes

for permissao in permissoes:
  if permissao == True:
    print('Tem permissão para dirigir')
  else:
    print('Não tem permissão para dirigir')

