# -*- coding: utf-8 -*-
"""Lógica de programação.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/195r7HN236HiPZdZta9aBTNSAVtf7jPRs

## **Lógica de programação**
"""

1+1

"Geneviê"

nome = "Geneviê"

nome

idade = 28

idade

print(' O nome é Guilherme e sua idade é 28 anos' )

print(f' O nome é {nome} e sua idade é {idade} anos' )

idade= 29

print(f' O nome é {nome} e sua idade é {idade} anos' )

"""## **Criando minha primeira função**"""

def saudacao():
  nome = input( 'Qual o seu nome? ')
  print(f'Olá {nome} ')

saudacao()

def nome_completo():
 primeiro_nome = input('Qual seu primeiro nome? ')
 sobrenome = input('Qual seu sobrenome? ')
 nome_inteiro = primeiro_nome + ' ' + sobrenome
 print(nome_inteiro)

nome_completo()

"""## **Parâmetros**"""

nome = 'Luiza'

def saudacao_com_parametro(nome_da_pessoa):
  print(f'Olá {nome_da_pessoa}')

saudacao_com_parametro(nome)



"""## **Condicional**"""

idade = 15

def verifica_idade(idade):
  if idade >= 18:
    print('Tem permissão para dirigir')
  else:
    print('Não tem permissão para dirigir')

verifica_idade(idade)

# Convertendo tipo para inteiro
def verifica_idade_sem_parametros():
  idade = input('Qual a sua idade?')
  idade = int(idade)

  if idade >= 18:
    print('Tem permissão para dirigir')
  else:
    print('Não tem permissão para dirigir')

verifica_idade_sem_parametros()

def verifica_idade_sem_parametros():
  idade = input('Qual a sua idade?')
  idade = int(idade)

  if idade >= 18:
    print('Tem permissão para dirigir')
  else:
    print('Não tem permissão para dirigir')

verifica_idade_sem_parametros()



